UPF to Tarski Converter
aiplan4eu/upf pull request #72
Opened 2021-12-23 10:25 UTC by Framba-Luca

2022-01-07 17:37 UTC, alvalentini commented on upf/solvers/upf_tarski_converter.py
> +                    typename = str(type).replace(' ','')
We need to consider int and real types with no bounds

2022-01-07 17:38 UTC, alvalentini commented on upf/solvers/upf_tarski_converter.py
> +                        if type.is_int_type() or type.is_real_type():
Keep them separate

2022-01-07 17:40 UTC, alvalentini commented on upf/solvers/upf_tarski_converter.py
> +                typename = str(fluent.type()).replace(' ','')
Same as above. Use `lang.Real()` and 'land.Integer()' when there are no bounds.

2022-01-07 17:40 UTC, alvalentini commented on upf/model/action.py
> +            if not (cond and set(self._preconditions) == set(oth._preconditions) and set(self._effects) == set(oth._effects)):
Remove all debug prints

2022-01-07 17:44 UTC, alvalentini commented on upf/interop/tarski.py
> +        if isinstance(func_sort, Interval):
As discussed, here we can treat `func_sort == 'Integer'` and `func_sort == 'Real'` as special cases

2022-01-07 17:45 UTC, alvalentini commented on upf/solvers/upf_tarski_converter.py
> +        return tarski.syntax.Constant(expression.int_constant_value(), self.lang.Real) # type: ignore
Why `lang.Real`?

2022-01-18 09:15 UTC, alvalentini requested changes

2022-01-18 09:15 UTC, alvalentini commented on upf/interop/from_tarski.py
> +            continue #NOTE: not sure
Check this note and fix it

2022-01-18 09:15 UTC, alvalentini commented on upf/interop/to_tarski.py
> +                        raise #NOTE is this raise right? If signature has ints/reals not
Fix this

2022-01-18 09:15 UTC, alvalentini commented on upf/interop/to_tarski.py
> +    #NOTE: Still missing the part where fluents can be of type user_type, not sure if this code works for it
Check this comment

2022-01-18 09:15 UTC, alvalentini commented on upf/walkers/type_checker.py
> +
```suggestion
```

2022-01-18 09:15 UTC, alvalentini commented on upf/walkers/type_checker.py
> +
```suggestion
```

2022-01-18 09:15 UTC, alvalentini commented on upf/interop/to_tarski.py
> +        return tarski_object_rep #NOTE :not sure
Why the note "not sure"?

2022-01-24 09:41 UTC, alvalentini requested changes

2022-01-24 09:41 UTC, alvalentini commented on upf/interop/to_tarski.py
> +        new_args = [x.constant_value() if x.is_int_constant() else args[i] for i, x in enumerate(expression.args())]
This line is useless

2022-01-24 09:41 UTC, alvalentini commented on upf/interop/to_tarski.py
> +                pass
Here we can raise an exception

2022-01-24 09:41 UTC, alvalentini commented on upf/interop/to_tarski.py
> +                for a in fluent_exp.args():#NOTE is this raise right? If signature has ints/reals not
```suggestion
                for a in fluent_exp.args():
```

2022-01-24 09:41 UTC, alvalentini commented on upf/io/pddl_reader.py
> +
```suggestion

```

2022-01-24 09:41 UTC, alvalentini commented on upf/test/test_a_tarski_grounder.py
> +    #TODO: add skipif
Fix it

2022-01-24 09:41 UTC, alvalentini commented on upf/test/test_a_tarski_grounder.py
> +    #TODO: write right skipif
Fix it

2022-01-24 09:41 UTC, alvalentini commented on upf/test/test_a_tarski_grounder.py
> +# Copyright 2021 AIPlan4EU project
Rename the file

2022-01-24 09:41 UTC, alvalentini commented on upf/transformers/grounder.py
> +            grounding_fluents_map: Optional[Dict[Fluent, Tuple[FNode, ...]]] = None):
This is not used, right?

2022-01-24 09:41 UTC, alvalentini commented on upf/transformers/grounder.py
> +                        self._old_to_new[old_action] = [new_action]
```suggestion
                if self._grounding_actions_map is None or \
                   self._grounding_actions_map.get(old_action, None) is not None:
                    new_action = old_action.clone()
                    self._new_problem.add_action(new_action)
                    self._new_to_old[new_action] = old_action
                    self._map_parameters[new_action] = []
                    self._old_to_new[old_action] = [new_action]
```

2022-01-24 09:41 UTC, alvalentini commented on upf/solvers/tarski_grounder.py
> +        #TODO: understand when LP works and when not and use the problem_kind instead of try-catch
Before calling the LPGroundingStrategy we should add a check like this:
```
gringo = shutil.which("gringo")
if gringo is None:
    raise CommandNotFoundError("gringo")
```

2022-01-24 09:41 UTC, alvalentini commented on upf/solvers/tarski_grounder.py
> +            actions = lpgs.ground_actions()
This command can throw a `ReachabilityLPUnsolvable` exception. We should handle it explicitly.

2022-01-24 13:51 UTC, mikand requested changes
Here are some comments

2022-01-24 16:15 UTC, alvalentini commented on upf/solvers/tarski_grounder.py
> +            raise upf.exceptions.UPFUsageError('tarski grounder can not be used for problems with continuous numbers.')
This is implicit from the `supports` method. Not needed here.

2022-01-24 17:43 UTC, alvalentini commented on upf/interop/to_tarski.py
> +                raise upf.exception.UPFProblemDefinitionError('Fluents can not have reals into their signatures.')
```suggestion
                raise upf.exceptions.UPFProblemDefinitionError('Fluents can not have reals into their signatures.')
```

2022-01-25 09:44 UTC, alvalentini requested changes

2022-01-25 09:44 UTC, alvalentini commented on upf/test/test_tarski_grounder.py
> +class TestGrounder(TestCase):
```suggestion
class TestTarskiGrounder(TestCase):
```

2022-01-25 09:44 UTC, alvalentini commented on upf/test/test_tarski_converter.py
> +class TestGrounder(TestCase):
```suggestion
class TestTarskiConverter(TestCase):
```

2022-01-25 09:44 UTC, alvalentini commented on upf/solvers/tarski_grounder.py
> +            raise tarski.errors.CommandNotFoundError('gringo not installed, try use sudo apt install gringo')
```suggestion
            raise tarski.errors.CommandNotFoundError('gringo')
```

2022-01-25 17:07 UTC, alvalentini approved these changes

2022-01-27 10:46 UTC, mikand approved these changes
@Framba-Luca Excellent work!

2022-01-27 10:46 UTC, mikand commented on upf/transformers/grounder.py
> +                grounded_params_list = _create_generator_from_list_of_tuple(self._grounding_actions_map[old_action])
There is no need for this function:
```suggestion
                grounded_params_list = iter(self._grounding_actions_map[old_action])
```

2022-01-27 10:46 UTC, mikand commented on upf/transformers/grounder.py
> +def _create_generator_from_list_of_tuple(tuple_list: List[Tuple[FNode, ...]]):
This function can be removed

2022-01-27 10:57 UTC, merged