Extend the PDDL reader
aiplan4eu/upf pull request #73
Opened 2022-01-04 16:48 UTC by alvalentini

2022-01-14 11:10 UTC, mikand requested changes
@alvalentini Excellent work! I left some comments to be fixed, then we can merge!

2022-01-14 11:10 UTC, mikand commented on upf/io/pddl_reader.py
> +    def parse_problem(self, domain_filename: str, problem_filename: str) -> 'upf.model.Problem':
An interesting feature could be to parse just the domain and get a partial `upf.model.Problem`: the use-case would be to have a fixed domain written in PDDL that gets instantiated with dynamic data. 

Would it be possible to make the `problem_filename` optional here?

2022-01-14 11:10 UTC, mikand commented on upf/io/pddl_reader.py
> +            for p in domain_res['predicates']:
```suggestion
        for p in domain_res.get('predicates', []):
```

2022-01-14 11:10 UTC, mikand commented on upf/io/pddl_reader.py
> +                self._add_effect(problem, act, e, cond, timing)
It should be very easy to remove recursion here: it suffices to implement a super-basic conjunctive partitioning like: https://github.com/pysmt/pysmt/blob/master/pysmt/rewritings.py#L856

2022-01-14 11:10 UTC, mikand commented on upf/io/pddl_reader.py
> +            return Times(-1, self._parse_exp(problem, act, var, exp[1]))
Maybe remove recursion here: it should be a matter of using a stack and a map for the results, no?

2022-01-14 11:10 UTC, mikand commented on upf/io/pddl_reader.py
> +                                raise upf.exceptions.UPFProblemDefinitionError(f'Not able to handle duration constraint of action {n}')
Maybe use a `SyntaxError` instead?

2022-01-14 11:10 UTC, mikand commented on upf/test/test_pddl_io.py
>      def test_matchcellar_writer(self):
Ad a few more tests: e.g. for each problems in UPF format, print them in PDDL and read them back asserting that the actions and initial states and goals are the same modulo reordering

2022-01-14 13:03 UTC, alvalentini commented on upf/io/pddl_reader.py
> +            return self._em.TRUE()
This happen only when we have something like `:precondition ()`

2022-01-18 13:19 UTC, mikand commented
@alvalentini Coverage is low because now  the module `interop.tarski` becomes untested. Can you add a few tests to recover a bit of coverage? Or shall we wait for #72 to restore the coverage?

2022-01-18 13:24 UTC, alvalentini commented
> @alvalentini Coverage is low because now the module `interop.tarski` becomes untested. Can you add a few tests to recover a bit of coverage? Or shall we wait for #72 to restore the coverage?

@mikand I think we can wait #72 that adds several tests about the `interop.tarski` module

2022-01-18 13:25 UTC, merged